version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/epiclogue.frontend
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
  - location: ./scripts/before-install.sh
    timeout: 300 # 5mins
    runas: root
  AfterInstall:
  - location: ./scripts/after-install.sh
    timeout: 300 # 5mins
    runas: root
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu