version: 0.0
os: linux
files:
        - source: /
          destination: /home/ubuntu/epiclogue.frontend
          overwrite: true
hooks:
        AfterInstall:
        - location: ./scripts/after-install.sh
          timeout: 300 # 5mins
          runas: root
