version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo 'Install npm dependencies...'
      - npm install
  build:
    commands:
      - echo 'Build started...'
      - npm run build
      - echo 'Build completed!'

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'

