version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo 'Install npm dependencies...'
      - npm install
  build:
    commands:
      - echo 'Build started...'
      - npm run build
      - echo 'Build completed!'
  post_build:
    commands:
      - echo 'Export started...'
      - npm run export
      - echo 'Export completed!'

artifacts:
  files:
    - out/**/*

cache:
  paths:
    - 'node_modules/**/*'
