export const LangMypage = {
  settingProfile: {
    2: 'Account Setting',
    0: '계정 설정',
    1: 'アカウント設定',
  },
  profileTab: {
    2: 'Account',
    0: '프로필',
    1: 'アカウント',
  },
  pushSetTab: {
    2: 'Notifications',
    0: '알림 설정',
    1: '通知設定',
  },
  generalSetTab: {
    2: 'Others Setting',
    0: '기본 설정',
    1: '基本設定',
  },
};

export const LangMypageProfile = {
  introPlaceHoder: {
    2: 'We are sure. What other people would want to know who I am',
    0: '내 소개를 통해 어필해보세요!',
    1: '私が誰なのか他の人々が気になると思いますよ?',
  },
  errorintro: {
    2: 'You can write up to 300 characters',
    0: '최대 300자 까지 작성이 가능해요',
    1: '最大300文字まで作成できます',
  },
  setChange: {
    2: 'Change',
    0: '변경하기',
    1: '変更する',
  },
  profileEmail: {
    2: 'Email',
    0: '이메일',
    1: '電子メール',
  },
  nickChange: {
    2: 'NickName',
    0: '닉네임',
    1: 'ニックネーム',
  },
  idChange: {
    2: 'ID',
    0: '아이디',
    1: 'アイディ',
  },
  pwChange: {
    2: 'Password',
    0: '비밀번호 변경',
    1: 'パスワード変更',
  },
  originPw: {
    2: 'Original Password',
    0: '기존 비밀번호',
    1: '既存のパスワード',
  },
  newPassword: {
    2: 'New Password',
    0: '새 비밀번호',
    1: '新しいパスワード',
  },
  confirmPw: {
    2: 'Password Confirm',
    0: '비밀번호 확인',
    1: 'パスワード確認',
  },
  widthDrawl: {
    2: 'Deactivate',
    0: '비활성화',
    1: '不活性化',
  },
  widthDrawlBtn: {
    2: 'Confirm',
    0: '비활성하기',
    1: '不活性化する',
  },
  widthDrawlAlert: {
    2: 'If you withdraw, the secondary creations uploaded by the other users about your original will not be deleted',
    0: '탈퇴를 하시면 원작에 대해 타유저가 업로드 한 2차 창작물은 삭제되지 않습니다',
    1: '退会後は、原作に対して他のユーザーがアップロードした2次創作物は削除されません',
  },
  changeSmallBtn: {
    2: 'Confirm',
    0: '변경',
    1: '変更',
  },
  changeNickError: {
    2: 'Please fill it out in 2 ~ 30 characters',
    0: '2 ~ 30자 내외로 작성해주세요',
    1: '2 ~ 30文字以内に作成してください',
  },
  changeIdError: {
    2: 'Please fill it out in 2 ~ 15 characters',
    0: '2 ~ 15자 내외로 작성해주세요',
    1: '2 ~ 15文字以内に作成してください',
  },
  alreadyId: {
    2: 'This ID is already in use',
    0: '이미 사용하고 있는 아이디에요',
    1: 'すでに使っているIDです',
  },
  originPwError: {
    2: 'The password is different from the old one',
    0: '기존 비밀번호와 달라요!',
    1: '既存のパスワードとは異なります',
  },
  changePwError: {
    2: 'Enter at least 8 characters, including numbers and special characters',
    0: '숫자와 특수문자 포함 8자 이상 입력해주세요',
    1: '数字と特殊文字を含めて8文字以上入力してください',
  },
  valiPwError: {
    2: `The new password doesn't match.`,
    0: '새 비밀번호가 일치하지 않아요 ',
    1: '新しいパスワードが一致しません。',
  },
  sizeError: {
    2: 'Banner and profile image sizes up to 10mb',
    0: '배너 및 프로필 이미지는 10mb 까지만 가능해요',
    1: 'バナー及びプロフィール画像は10mbまでです',
  },
};

export const LangMypageInform = {
  pushSetting: {
    2: 'Push Setting',
    0: '푸시 설정',
    1: 'プッシュ設定',
  },
  pushSetDesc: {
    2: 'Check whether the Push Tab is visible on the user screen',
    0: '알림 상자가 유저 화면에 보이는지 여부를 확인합니다',
    1: 'プッシュがユーザー画面に表示されるかどうかを確認します',
  },
  generalSetting: {
    2: 'General Setting',
    0: '일반 설정',
    1: '一般設定',
  },
  generalSetDesc: {
    2: 'Set up all notifications generated by user interaction',
    0: '유저간 상호작용으로 일어나는 모든 알림을 설정합니다',
    1: 'ユーザーの相互作用で起こるすべての通知を設定します',
  },
};

export const LangMypageGene = {
  contrySetting: {
    2: 'Contry Setting',
    0: '국가 설정',
    1: '国家設定',
  },
  viewLanguage: {
    2: 'Set display language',
    0: '표시 언어 설정',
    1: '表示言語設定',
  },
  InterestLanguage: {
    2: 'Language of interest',
    0: '관심 언어',
    1: '見たい言語',
  },
  InterestLangDesc: {
    2: 'You can view your contributions in the selected language',
    0: '선택한 언어의 작품이 보여집니다',
    1: '選択した言語の作品が表示されます',
  },
  muteSetting: {
    2: 'Mute Setting',
    0: '뮤트 설정',
    1: 'ミュート設定',
  },
  muteSetDesc: {
    2: 'Manages the interaction of muted users',
    0: '뮤트한 유저의 상호작용을 관리합니다',
    1: 'ミュートなユーザーのインタラクションを管理します',
  },
  changeBtn: {
    2: 'Change',
    0: '변경하기',
    1: '変更する',
  },
};
